server:
  port: 8003
mybatis:
  type-aliases-package: com.yf.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring 配置
spring:
  application:
    name: spring-cloud-privider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: yf1234


#eureka配置，服务注册到哪里？
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: spring-cloud-provider-dept8003 #修改eureka上的配置信息

#info信息
info:
  app.name: yf-springcloud
  company.name: baidu.com