server:
  port: 9527

# spring 配置
spring:
  application:
    name: spring-cloud-zuul



#eureka配置，服务注册到哪里？
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: spring-cloud-zuul-9527 #修改eureka上的配置信息
    prefer-ip-address: true

#info信息
info:
  app.name: spring-cloud-zuul-9527
  company.name: baidu.com
