server:
  port: 7001


#Eureka配置
eureka:
  instance:
    hostname: localhost #eureka服务器的实例名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册
    fetch-registry: false  #如果为false,则表示自己为注册中心
    server-url:             #EurekaClientConfigBean
      defaultZone:http://${eureka.instance.hostname}:${service.port}/eureka/
